# Generated by Django 4.1.4 on 2022-12-20 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='timg',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='tname',
            new_name='name',
        ),
    ]
